language: node_js
node_js:
  - 0.8
notifications:
  email:
    recipients:
      - lukas@apiary.io
    on_success: change
    on_failure: always
  hipchat:
    - secure: "HqBUrmf4P2bgvwb4b9PL1tBae2wcZaXadOgwRwAFhdhDZFHaKXIXlJRUW8tN\ntdO83OZgatxJrpWWQj8VYTfDuhlE3b3NxVWeXc3PkfrHmuvejQf4veh7kwR0\njLVE6jb+ZbFIwRE2W0VFLFKYQHI6PLem4W0OKXW5Shqzy8Ewlow="
  irc:
    channels: "irc.freenode.org#apiary"
    on_success: always
    on_failure: always

cache:
  directories:
    - node_modules

